"""
Task 5 Notebook Updater
Injects the full semantic segmentation + colorization + gradio GUI implementation.
Run this script from the Task5_Semantic_Segmentation directory.
"""

import json
import os

NOTEBOOK_PATH = "semantic_segmentation.ipynb"

cells = [
    # ─── CELL 0 – TITLE ───────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_title",
        "metadata": {},
        "source": [
            "# Task 5: Semantic Segmentation for Targeted Colorization\n",
            "### Internship – Real-time Gen AI Image Colorization\n",
            "\n",
            "> **Task Description**: Implement a model that employs semantic segmentation to "
            "colorize particular portions of an image (e.g. only the foreground or "
            "background). The model should let users choose which regions to colorize. "
            "A graphical user interface should be given to allow for region selection "
            "and result previews.\n",
            "\n",
            "### Pipeline Overview\n",
            "```\n",
            "Grayscale Image\n",
            "      │\n",
            "      ▼\n",
            "DeepLabV3 Segmentation  ──►  21-class mask (VOC palette)\n",
            "      │\n",
            "      ▼\n",
            "User selects region(s)  ──►  Binary mask (0/1)\n",
            "      │\n",
            "      ▼\n",
            "Colorization Network (LAB) ─►  AB channels predicted\n",
            "      │\n",
            "      ▼\n",
            "Mask Composite          ──►  Only selected region gets color\n",
            "      │\n",
            "      ▼\n",
            "Gradio GUI for interactive preview\n",
            "```"
        ]
    },

    # ─── CELL 1 – INSTALLS ────────────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_install",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Install required packages\n",
            "import subprocess, sys\n",
            "pkgs = ['gradio', 'scikit-image', 'tqdm', 'opencv-python']\n",
            "for p in pkgs:\n",
            "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', p])\n",
            "print('✅ All packages ready!')"
        ]
    },

    # ─── CELL 2 – IMPORTS / DEVICE ────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_imports",
        "metadata": {},
        "outputs": [],
        "source": [
            "import os, gc, warnings\n",
            "warnings.filterwarnings('ignore')\n",
            "os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'python'\n",
            "os.environ['CUDA_MODULE_LOADING'] = 'LAZY'\n",
            "\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.optim as optim\n",
            "from torch.utils.data import DataLoader, Dataset\n",
            "from torchvision import models, transforms\n",
            "import numpy as np\n",
            "from PIL import Image\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.patches as mpatches\n",
            "from skimage import color\n",
            "from tqdm import tqdm\n",
            "import cv2\n",
            "\n",
            "# ── Device Setup ──────────────────────────────────────────────────────\n",
            "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "DTYPE  = torch.float16 if torch.cuda.is_available() else torch.float32\n",
            "print(f'🖥️  Device : {DEVICE}')\n",
            "if torch.cuda.is_available():\n",
            "    print(f'🎮  GPU    : {torch.cuda.get_device_name(0)}')\n",
            "    print(f'💾  VRAM   : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')"
        ]
    },

    # ─── CELL 3 – VOC CLASS MAP (markdown) ────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_voc",
        "metadata": {},
        "source": [
            "## Step 1 – VOC-21 Semantic Class Map\n",
            "DeepLabV3 is pre-trained on Pascal VOC which has **21 classes** (0 = background).\n",
            "We group them into user-friendly categories so the GUI is intuitive."
        ]
    },

    # ─── CELL 4 – VOC CLASS DEFS ──────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_voc_classes",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Pascal VOC 21-class labels (index → name)\n",
            "VOC_CLASSES = [\n",
            "    'background', 'aeroplane', 'bicycle', 'bird', 'boat', 'bottle',\n",
            "    'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog',\n",
            "    'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa',\n",
            "    'train', 'tvmonitor'\n",
            "]\n",
            "\n",
            "# User-friendly group → list of VOC class indices\n",
            "REGION_GROUPS = {\n",
            "    'Background Only'   : [0],\n",
            "    'People / Persons'  : [15],\n",
            "    'Animals'           : [3, 8, 10, 12, 13, 17],   # bird,cat,cow,dog,horse,sheep\n",
            "    'Vehicles'          : [1, 2, 4, 6, 7, 14, 19],  # plane,bicycle,boat,bus,car,moto,train\n",
            "    'Indoor Objects'    : [9, 11, 16, 18, 20],      # chair,table,plant,sofa,tv\n",
            "    'All Foreground'    : list(range(1, 21)),\n",
            "    'Everything (Full)' : list(range(0, 21)),\n",
            "}\n",
            "\n",
            "print('📋 Available region groups:')\n",
            "for k, v in REGION_GROUPS.items():\n",
            "    labels = [VOC_CLASSES[i] for i in v]\n",
            "    print(f'   {k:24s} → {labels}')"
        ]
    },

    # ─── CELL 5 – SEGMENTATION MODEL ──────────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_seg",
        "metadata": {},
        "source": [
            "## Step 2 – Load DeepLabV3-ResNet50 Segmentation Model\n",
            "We use the **pretrained** DeepLabV3 from torchvision (no training required for this step)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_load_seg",
        "metadata": {},
        "outputs": [],
        "source": [
            "print('⏳ Loading DeepLabV3-ResNet50 segmentation model...')\n",
            "seg_model = models.segmentation.deeplabv3_resnet50(\n",
            "    weights=models.segmentation.DeepLabV3_ResNet50_Weights.DEFAULT\n",
            ").to(DEVICE).eval()\n",
            "print('✅ Segmentation model ready!')\n",
            "\n",
            "# ImageNet normalization required by DeepLabV3\n",
            "SEG_TRANSFORM = transforms.Compose([\n",
            "    transforms.ToTensor(),\n",
            "    transforms.Normalize(mean=[0.485, 0.456, 0.406],\n",
            "                         std =[0.229, 0.224, 0.225]),\n",
            "])\n",
            "\n",
            "def run_segmentation(pil_rgb: Image.Image) -> np.ndarray:\n",
            "    \"\"\"Returns a (H, W) array of VOC class indices (0-20).\"\"\"\n",
            "    inp = SEG_TRANSFORM(pil_rgb).unsqueeze(0).to(DEVICE)\n",
            "    with torch.no_grad():\n",
            "        out = seg_model(inp)['out'][0]   # (21, H, W)\n",
            "    return out.argmax(0).cpu().numpy().astype(np.uint8)\n",
            "\n",
            "\n",
            "def build_mask(seg_map: np.ndarray, region: str) -> np.ndarray:\n",
            "    \"\"\"Returns binary mask (H, W) True = colorize this pixel.\"\"\"\n",
            "    class_ids = REGION_GROUPS.get(region, list(range(21)))\n",
            "    mask = np.zeros_like(seg_map, dtype=bool)\n",
            "    for cid in class_ids:\n",
            "        mask |= (seg_map == cid)\n",
            "    return mask\n",
            "\n",
            "print('✅ Segmentation helpers defined!')"
        ]
    },

    # ─── CELL 6 – COLORIZATION NETWORK ────────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_color_net",
        "metadata": {},
        "source": [
            "## Step 3 – Colorization Network (LAB Color Space)\n",
            "A lightweight encoder-decoder CNN that takes the **L** (lightness) channel as input\n",
            "and predicts the **AB** (chrominance) channels.  This is trained on COCO images.\n",
            "\n",
            "The segmentation mask is later used to **composite** the predicted colors:\n",
            "only pixels inside the selected region receive the AI-predicted color."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_color_net",
        "metadata": {},
        "outputs": [],
        "source": [
            "class ColorizationNet(nn.Module):\n",
            "    \"\"\"Lightweight encoder-decoder for AB channel prediction.\"\"\"\n",
            "    def __init__(self):\n",
            "        super().__init__()\n",
            "        def _block(ci, co, stride=2):\n",
            "            return nn.Sequential(\n",
            "                nn.Conv2d(ci, co, 3, stride=stride, padding=1),\n",
            "                nn.BatchNorm2d(co), nn.LeakyReLU(0.2, inplace=True)\n",
            "            )\n",
            "        def _up(ci, co):\n",
            "            return nn.Sequential(\n",
            "                nn.ConvTranspose2d(ci, co, 3, stride=2, padding=1, output_padding=1),\n",
            "                nn.BatchNorm2d(co), nn.ReLU(inplace=True)\n",
            "            )\n",
            "        self.enc1 = _block(1,   64)\n",
            "        self.enc2 = _block(64,  128)\n",
            "        self.enc3 = _block(128, 256)\n",
            "        self.enc4 = _block(256, 512)\n",
            "\n",
            "        self.dec1 = _up(512, 256)\n",
            "        self.dec2 = _up(512, 128)   # skip from enc3\n",
            "        self.dec3 = _up(256, 64)    # skip from enc2\n",
            "        self.dec4 = _up(128, 32)    # skip from enc1\n",
            "\n",
            "        self.head = nn.Sequential(\n",
            "            nn.Conv2d(32, 2, 3, padding=1),\n",
            "            nn.Tanh()\n",
            "        )\n",
            "\n",
            "    def forward(self, x):\n",
            "        e1 = self.enc1(x)\n",
            "        e2 = self.enc2(e1)\n",
            "        e3 = self.enc3(e2)\n",
            "        e4 = self.enc4(e3)\n",
            "        d  = self.dec1(e4)\n",
            "        d  = self.dec2(torch.cat([d, e3], 1))\n",
            "        d  = self.dec3(torch.cat([d, e2], 1))\n",
            "        d  = self.dec4(torch.cat([d, e1], 1))\n",
            "        return self.head(d)\n",
            "\n",
            "\n",
            "def lab_to_rgb(L_t: torch.Tensor, AB_t: torch.Tensor) -> np.ndarray:\n",
            "    \"\"\"Convert L (1,H,W) + AB (2,H,W) tensors → RGB uint8 numpy.\"\"\"\n",
            "    L_np  = (L_t.squeeze().cpu().float().numpy()  + 1.0) * 50.0\n",
            "    AB_np = AB_t.squeeze().cpu().float().numpy().transpose(1, 2, 0) * 128.0\n",
            "    h, w  = L_np.shape\n",
            "    lab   = np.zeros((h, w, 3), dtype=np.float64)\n",
            "    lab[:, :, 0]  = L_np\n",
            "    lab[:, :, 1:] = AB_np\n",
            "    return (color.lab2rgb(lab) * 255).clip(0, 255).astype(np.uint8)\n",
            "\n",
            "\n",
            "print('✅ ColorizationNet (U-Net with skip connections) defined!')\n",
            "print(f'   Parameters: {sum(p.numel() for p in ColorizationNet().parameters()):,}')"
        ]
    },

    # ─── CELL 7 – DATASET ─────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_dataset",
        "metadata": {},
        "source": [
            "## Step 4 – Dataset: Auto-discover COCO Images\n",
            "We locate all JPEG images from the Task 4 dataset (saves re-downloading)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_dataset",
        "metadata": {},
        "outputs": [],
        "source": [
            "import glob, random\n",
            "\n",
            "# ── Locate images (Task 4 dataset / any nearby folder) ────────────────\n",
            "SEARCH_ROOTS = [\n",
            "    '../Task4_Data_Augmentation/dataset/train',\n",
            "    '../Task4_Data_Augmentation/dataset/test',\n",
            "    '../Task4_Data_Augmentation/val2017',\n",
            "    'dataset/train', 'dataset/test',\n",
            "]\n",
            "\n",
            "all_images = []\n",
            "for root in SEARCH_ROOTS:\n",
            "    found = glob.glob(os.path.join(root, '**', '*.jpg'), recursive=True)\n",
            "    all_images.extend(found)\n",
            "\n",
            "# Remove duplicates & corrupt files\n",
            "seen, clean = set(), []\n",
            "for p in all_images:\n",
            "    rp = os.path.realpath(p)\n",
            "    if rp in seen or os.path.getsize(p) < 2000: continue\n",
            "    try: Image.open(p).verify(); seen.add(rp); clean.append(p)\n",
            "    except: pass\n",
            "\n",
            "random.seed(42)\n",
            "random.shuffle(clean)\n",
            "TRAIN_IMGS = clean[:int(len(clean) * 0.9)]\n",
            "TEST_IMGS  = clean[int(len(clean) * 0.9):]\n",
            "\n",
            "print(f'📦 Found {len(clean)} clean images  |  train={len(TRAIN_IMGS)}, test={len(TEST_IMGS)}')\n",
            "if len(clean) == 0:\n",
            "    print('⚠️  No images found. Make sure Task 4 dataset exists at ../Task4_Data_Augmentation/dataset/')\n",
            "\n",
            "\n",
            "# ── PyTorch Dataset ────────────────────────────────────────────────────\n",
            "IMG_SIZE = 256\n",
            "\n",
            "class SegColorizationDataset(Dataset):\n",
            "    def __init__(self, paths, augment=False):\n",
            "        self.paths   = paths\n",
            "        self.augment = augment\n",
            "        self.aug = transforms.Compose([\n",
            "            transforms.RandomResizedCrop(IMG_SIZE, scale=(0.6, 1.0)),\n",
            "            transforms.RandomHorizontalFlip(),\n",
            "        ])\n",
            "        self.base = transforms.Resize((IMG_SIZE, IMG_SIZE))\n",
            "\n",
            "    def __len__(self): return len(self.paths)\n",
            "\n",
            "    def __getitem__(self, idx):\n",
            "        try:\n",
            "            img = Image.open(self.paths[idx]).convert('RGB')\n",
            "        except:\n",
            "            return self.__getitem__((idx + 1) % len(self))\n",
            "        img = self.aug(img) if self.augment else self.base(img)\n",
            "        lab = color.rgb2lab(np.array(img))\n",
            "        L   = torch.FloatTensor(lab[:, :, 0] / 50.0 - 1.0).unsqueeze(0)\n",
            "        AB  = torch.FloatTensor(lab[:, :, 1:] / 128.0).permute(2, 0, 1)\n",
            "        return L, AB\n",
            "\n",
            "print('✅ Dataset class ready!')"
        ]
    },

    # ─── CELL 8 – TRAIN ───────────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_train",
        "metadata": {},
        "source": [
            "## Step 5 – Train the Colorization Network\n",
            "We train for **50 epochs** using **L1 Loss** (better color saturation than MSE).\n",
            "The trained model is saved to `colorization_model.pth`."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_train",
        "metadata": {},
        "outputs": [],
        "source": [
            "MODEL_PATH = 'colorization_model.pth'\n",
            "EPOCHS     = 50\n",
            "BATCH_SIZE = 8\n",
            "LR         = 1e-3\n",
            "\n",
            "colorization_model = ColorizationNet().to(DEVICE)\n",
            "\n",
            "if os.path.exists(MODEL_PATH):\n",
            "    colorization_model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))\n",
            "    print(f'✅ Loaded existing model from {MODEL_PATH}  – skip re-training, or delete to retrain.')\n",
            "elif len(TRAIN_IMGS) == 0:\n",
            "    print('⚠️  No training images available. Model weights will be random – results will be poor.')\n",
            "    print('   Add images to Task4_Data_Augmentation/dataset/train/ or run Task 4 first.')\n",
            "else:\n",
            "    train_ds = SegColorizationDataset(TRAIN_IMGS, augment=True)\n",
            "    loader   = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,\n",
            "                          num_workers=0, pin_memory=torch.cuda.is_available())\n",
            "\n",
            "    criterion = nn.L1Loss()\n",
            "    optimizer = optim.Adam(colorization_model.parameters(), lr=LR)\n",
            "    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-5)\n",
            "\n",
            "    losses = []\n",
            "    print(f'🚀 Training for {EPOCHS} epochs on {len(TRAIN_IMGS)} images...')\n",
            "    for epoch in range(EPOCHS):\n",
            "        colorization_model.train()\n",
            "        epoch_loss = 0.0\n",
            "        for L, AB in tqdm(loader, desc=f'Epoch {epoch+1}/{EPOCHS}', leave=False):\n",
            "            L, AB = L.to(DEVICE), AB.to(DEVICE)\n",
            "            optimizer.zero_grad()\n",
            "            pred = colorization_model(L)\n",
            "            loss = criterion(pred, AB)\n",
            "            loss.backward()\n",
            "            optimizer.step()\n",
            "            epoch_loss += loss.item()\n",
            "        scheduler.step()\n",
            "        avg = epoch_loss / len(loader)\n",
            "        losses.append(avg)\n",
            "        if (epoch + 1) % 10 == 0:\n",
            "            print(f'  Epoch {epoch+1:3d}/{EPOCHS} | L1 Loss: {avg:.4f}')\n",
            "        gc.collect(); torch.cuda.empty_cache()\n",
            "\n",
            "    torch.save(colorization_model.state_dict(), MODEL_PATH)\n",
            "    print(f'\\n✅ Training complete! Model saved → {MODEL_PATH}')\n",
            "\n",
            "    plt.figure(figsize=(8, 3))\n",
            "    plt.plot(losses, color='royalblue')\n",
            "    plt.xlabel('Epoch'); plt.ylabel('L1 Loss')\n",
            "    plt.title('Training Loss Curve – Task 5 Colorization Model')\n",
            "    plt.tight_layout(); plt.savefig('training_loss.png', dpi=120)\n",
            "    plt.show()\n",
            "    print('📊 Loss curve saved → training_loss.png')\n",
            "\n",
            "colorization_model.eval()\n",
            "print('\\n✅ Model is ready for inference!')"
        ]
    },

    # ─── CELL 9 – COMPOSITE PIPELINE ──────────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_composite",
        "metadata": {},
        "source": [
            "## Step 6 – Targeted Colorization Pipeline\n",
            "The core function that:\n",
            "1. Segments the image (DeepLabV3)\n",
            "2. Builds a binary mask for the selected region\n",
            "3. Predicts AB colors for the whole image\n",
            "4. **Composites**: only pixels inside the mask receive color — the rest stays grayscale"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_pipeline",
        "metadata": {},
        "outputs": [],
        "source": [
            "def targeted_colorize(\n",
            "    pil_input:  Image.Image,\n",
            "    region:     str  = 'All Foreground',\n",
            "    intensity:  float = 1.0,\n",
            "    show_mask:  bool  = False,\n",
            ") -> tuple:\n",
            "    \"\"\"\n",
            "    Returns (colorized_pil, mask_pil, seg_overlay_pil).\n",
            "\n",
            "    Parameters\n",
            "    ----------\n",
            "    pil_input  : PIL RGB image (any size)\n",
            "    region     : one of REGION_GROUPS keys\n",
            "    intensity  : 0.0 = no color, 1.0 = full color, >1.0 = vivid\n",
            "    show_mask  : whether to draw mask overlay\n",
            "    \"\"\"\n",
            "    # 1. Resize to working size\n",
            "    img_rgb = pil_input.convert('RGB').resize((IMG_SIZE, IMG_SIZE), Image.LANCZOS)\n",
            "\n",
            "    # 2. Segmentation\n",
            "    seg_map = run_segmentation(img_rgb)   # (H, W) uint8\n",
            "    mask    = build_mask(seg_map, region) # (H, W) bool\n",
            "\n",
            "    # 3. Prepare L channel\n",
            "    img_np = np.array(img_rgb)\n",
            "    lab    = color.rgb2lab(img_np)\n",
            "    L_np   = lab[:, :, 0]\n",
            "    L_t    = torch.FloatTensor(L_np / 50.0 - 1.0).unsqueeze(0).unsqueeze(0).to(DEVICE)\n",
            "\n",
            "    # 4. Predict AB\n",
            "    with torch.no_grad():\n",
            "        AB_pred = colorization_model(L_t)   # (1, 2, H, W)\n",
            "\n",
            "    AB_np = AB_pred.squeeze().cpu().float().numpy().transpose(1, 2, 0) * 128.0\n",
            "\n",
            "    # 5. Composite: apply intensity & mask\n",
            "    AB_out = np.zeros_like(AB_np)          # default = grayscale (AB = 0)\n",
            "    AB_out[mask] = AB_np[mask] * intensity # colorize only masked pixels\n",
            "\n",
            "    result_lab          = lab.copy()\n",
            "    result_lab[:, :, 1:] = AB_out\n",
            "    result_rgb = (color.lab2rgb(result_lab) * 255).clip(0, 255).astype(np.uint8)\n",
            "\n",
            "    # 6. Mask visualization\n",
            "    mask_vis = (mask.astype(np.uint8) * 255)\n",
            "    mask_rgb = np.stack([mask_vis, mask_vis, mask_vis], -1)\n",
            "\n",
            "    # 7. Segmentation color overlay\n",
            "    PALETTE = plt.cm.get_cmap('tab20', 21)\n",
            "    seg_colored = (PALETTE(seg_map / 20.0)[:, :, :3] * 255).astype(np.uint8)\n",
            "    overlay = (img_np * 0.5 + seg_colored * 0.5).clip(0, 255).astype(np.uint8)\n",
            "\n",
            "    return (\n",
            "        Image.fromarray(result_rgb),\n",
            "        Image.fromarray(mask_rgb),\n",
            "        Image.fromarray(overlay),\n",
            "        {VOC_CLASSES[i]: int(np.sum(seg_map == i)) for i in np.unique(seg_map)}\n",
            "    )\n",
            "\n",
            "print('✅ targeted_colorize() pipeline ready!')"
        ]
    },

    # ─── CELL 10 – QUICK DEMO ─────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_demo",
        "metadata": {},
        "source": [
            "## Step 7 – Quick Visualization Demo\n",
            "Test the pipeline on a real image from the dataset."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_demo",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Use a test image if available, otherwise create a synthetic one\n",
            "if TEST_IMGS:\n",
            "    demo_path = TEST_IMGS[0]\n",
            "    demo_img  = Image.open(demo_path).convert('RGB')\n",
            "    print(f'🖼️  Demo image: {demo_path}')\n",
            "else:\n",
            "    # Synthetic checkerboard grayscale\n",
            "    arr = np.tile(np.kron([[200, 100] * 8] * 8 + [[100, 200] * 8] * 8, np.ones((16,16))), (1,1))\n",
            "    arr = arr[:256, :256].astype(np.uint8)\n",
            "    demo_img = Image.fromarray(np.stack([arr, arr, arr], -1))\n",
            "    print('⚠️  No test images found – using synthetic checkerboard.')\n",
            "\n",
            "# ── Run pipeline for two regions ──────────────────────────────────────\n",
            "regions_to_show = ['Background Only', 'All Foreground']\n",
            "fig, axes = plt.subplots(1, 2 + len(regions_to_show), figsize=(18, 5))\n",
            "\n",
            "axes[0].imshow(demo_img.convert('L'), cmap='gray')\n",
            "axes[0].set_title('Input (Grayscale view)', fontsize=12, fontweight='bold')\n",
            "axes[0].axis('off')\n",
            "\n",
            "seg_map_demo = run_segmentation(demo_img.convert('RGB').resize((IMG_SIZE, IMG_SIZE)))\n",
            "PALETTE = plt.cm.get_cmap('tab20', 21)\n",
            "axes[1].imshow(PALETTE(seg_map_demo / 20.0))\n",
            "detected = [VOC_CLASSES[i] for i in np.unique(seg_map_demo)]\n",
            "axes[1].set_title(f'Segmentation Map\\n{detected}', fontsize=10)\n",
            "axes[1].axis('off')\n",
            "\n",
            "for ax, region in zip(axes[2:], regions_to_show):\n",
            "    result, mask_pil, overlay_pil, class_counts = targeted_colorize(demo_img, region=region)\n",
            "    ax.imshow(result)\n",
            "    ax.set_title(f'Colorized: {region}', fontsize=11, fontweight='bold')\n",
            "    ax.axis('off')\n",
            "\n",
            "plt.suptitle('Task 5 – Semantic Segmentation Targeted Colorization', fontsize=14, fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.savefig('task5_demo.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()\n",
            "print('\\n✅ Demo complete! Saved → task5_demo.png')\n",
            "print(f'📊 Detected classes: {detected}')"
        ]
    },

    # ─── CELL 11 – GRADIO GUI ─────────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "id": "md_gui",
        "metadata": {},
        "source": [
            "## Step 8 – Interactive Gradio GUI\n",
            "A full GUI with:\n",
            "- **Image upload** (any color or grayscale image)\n",
            "- **Region selector** (Background / People / Animals / Vehicles / All Foreground / Everything)\n",
            "- **Color intensity slider** (0 = grayscale → 1 = normal → 1.5 = vivid)\n",
            "- **Three output panels**: Colorized result | Binary mask | Segmentation overlay"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "cell_gradio",
        "metadata": {},
        "outputs": [],
        "source": [
            "import gradio as gr\n",
            "\n",
            "def gradio_colorize(image, region, intensity):\n",
            "    if image is None:\n",
            "        return None, None, None, 'No image uploaded.'\n",
            "    pil_img = Image.fromarray(image).convert('RGB')\n",
            "    try:\n",
            "        result, mask_pil, overlay_pil, class_counts = targeted_colorize(\n",
            "            pil_img, region=region, intensity=float(intensity)\n",
            "        )\n",
            "        info = '**Detected classes in image:**\\n'\n",
            "        for cls, cnt in sorted(class_counts.items(), key=lambda x: -x[1]):\n",
            "            pct = cnt / (IMG_SIZE * IMG_SIZE) * 100\n",
            "            info += f'  • `{cls}`: {pct:.1f}% of image\\n'\n",
            "        return np.array(result), np.array(mask_pil), np.array(overlay_pil), info\n",
            "    except Exception as e:\n",
            "        return None, None, None, f'❌ Error: {str(e)}'\n",
            "\n",
            "\n",
            "with gr.Blocks(\n",
            "    title='Task 5 – Semantic Segmentation Colorization',\n",
            "    theme=gr.themes.Soft(primary_hue='blue', neutral_hue='slate'),\n",
            "    css='h1 { text-align: center; } .gr-button-primary { background: #2563eb !important; }'\n",
            ") as demo:\n",
            "\n",
            "    gr.Markdown('# 🎨 Task 5: Semantic Segmentation Targeted Colorization')\n",
            "    gr.Markdown(\n",
            "        'Upload a **grayscale or color** image. Select the **region** you want to colorize. '\n",
            "        'The AI segments the scene and applies color **only to that area**.'\n",
            "    )\n",
            "\n",
            "    with gr.Row():\n",
            "        # ── Left column: inputs ──────────────────────────────────\n",
            "        with gr.Column(scale=1):\n",
            "            gr.Markdown('### 📤 Input')\n",
            "            input_img = gr.Image(\n",
            "                label='Upload Image (grayscale or color)',\n",
            "                type='numpy', height=300\n",
            "            )\n",
            "            region_sel = gr.Dropdown(\n",
            "                choices=list(REGION_GROUPS.keys()),\n",
            "                value='All Foreground',\n",
            "                label='🗂️ Region to Colorize',\n",
            "                info='Which semantic region should receive color?'\n",
            "            )\n",
            "            intensity_sl = gr.Slider(\n",
            "                minimum=0.0, maximum=2.0, value=1.0, step=0.05,\n",
            "                label='🌈 Color Intensity',\n",
            "                info='0 = grayscale  |  1.0 = natural  |  2.0 = vivid'\n",
            "            )\n",
            "            run_btn = gr.Button('▶  Run Targeted Colorization', variant='primary', size='lg')\n",
            "\n",
            "        # ── Right column: outputs ─────────────────────────────────\n",
            "        with gr.Column(scale=2):\n",
            "            gr.Markdown('### 📥 Results')\n",
            "            with gr.Row():\n",
            "                out_colorized = gr.Image(label='✅ Colorized Output',     type='numpy', height=280)\n",
            "                out_mask      = gr.Image(label='🎭 Region Mask (white=colorized)', type='numpy', height=280)\n",
            "                out_seg       = gr.Image(label='🗺️ Segmentation Overlay', type='numpy', height=280)\n",
            "            out_info = gr.Markdown('*Run the model to see detected classes.*')\n",
            "\n",
            "    gr.Markdown('---')\n",
            "    gr.Markdown('### 💡 Tips')\n",
            "    gr.Markdown(\n",
            "        '- Use **People / Persons** to colorize only humans in the scene.\\n'\n",
            "        '- Use **Background Only** to colorize walls, floors, sky — not the subjects.\\n'\n",
            "        '- Use **Animals** to colorize pets and livestock only.\\n'\n",
            "        '- Drag the intensity slider above 1.0 for more vivid, saturated results.\\n'\n",
            "        '- The **Segmentation Overlay** shows what the AI detects — hover over the image.'\n",
            "    )\n",
            "\n",
            "    run_btn.click(\n",
            "        fn=gradio_colorize,\n",
            "        inputs=[input_img, region_sel, intensity_sl],\n",
            "        outputs=[out_colorized, out_mask, out_seg, out_info]\n",
            "    )\n",
            "\n",
            "\n",
            "print('🚀 Launching Gradio GUI...')\n",
            "demo.queue().launch(share=True)\n"
        ]
    }
]

# ── Load existing notebook metadata ──────────────────────────────────────────
with open(NOTEBOOK_PATH, encoding='utf-8') as f:
    nb = json.load(f)

nb['cells'] = cells
nb['metadata']['kernelspec'] = {
    "display_name": "Python (image_gen)",
    "language": "python",
    "name": "image_gen"
}

with open(NOTEBOOK_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"✅ {NOTEBOOK_PATH} updated with {len(cells)} cells!")
print("📌 Next steps:")
print("   1. Open Jupyter and navigate to Task5_Semantic_Segmentation/")
print("   2. Open semantic_segmentation.ipynb")
print("   3. Run All Cells (Kernel > Restart & Run All)")
